import { useMemo, useState } from 'react'
import ClientContactActions from './components/ClientContactActions/ClientContactActions.jsx'

const advocates = [
  { name: 'Harvikramjit Singh Oberoi', role: 'Lead Partner · NRI Special Desk', image: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?auto=format&fit=crop&w=700&q=85', practice: 'NRI & Cross-Border', court: 'Supreme Court', location: 'New Delhi', years: 24, rating: '4.9', matters: '1,240', languages: 'English · Hindi · Punjabi', badge: 'NRI Global Desk' },
  { name: 'Meenakshi Sundaram', role: 'Senior Partner · Infrastructure & Land Laws', image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=700&q=85', practice: 'Property & Succession', court: 'Delhi High Court', location: 'New Delhi', years: 19, rating: '4.8', matters: '980', languages: 'English · Hindi · Tamil', badge: 'Verified Counsel' },
  { name: 'Rajeshwar Rao, LL.M.', role: 'Managing Partner · Corporate & Insolvency', image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=700&q=85', practice: 'Corporate & Arbitration', court: 'NCLT / NCLAT', location: 'Mumbai', years: 21, rating: '4.9', matters: '760', languages: 'English · Hindi · Telugu', badge: 'Enterprise Counsel' },
  { name: 'Vikramaditya Chawla', role: 'Special Counsel · White Collar Defence', image: 'https://images.unsplash.com/photo-1556157382-8c8a5d9b2f07?auto=format&fit=crop&w=700&q=85', practice: 'Criminal Defence', court: 'Supreme Court', location: 'New Delhi', years: 28, rating: '4.9', matters: '1,860', languages: 'English · Hindi · Punjabi', badge: 'Urgent Response' },
  { name: 'K. N. Venkatachalam, AoR', role: 'Advocate-on-Record · Constitutional Law', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=700&q=85', practice: 'Constitutional & Appellate', court: 'Supreme Court', location: 'New Delhi', years: 32, rating: '5.0', matters: '2,100', languages: 'English · Hindi · Malayalam', badge: 'Apex Roster' },
  { name: 'Ananya Deshmukh', role: 'Lead Partner · Family & Private Wealth', image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=700&q=85', practice: 'Family & Matrimonial', court: 'Bombay High Court', location: 'Mumbai', years: 17, rating: '4.8', matters: '640', languages: 'English · Hindi · Marathi', badge: 'Private Chambers' },
  { name: 'Rohan Singhania', role: 'Lead Counsel · Intellectual Property Wing', image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=700&q=85', practice: 'Intellectual Property', court: 'Delhi High Court', location: 'New Delhi', years: 15, rating: '4.7', matters: '520', languages: 'English · Hindi · Gujarati', badge: 'IP Specialist' },
  { name: 'Harishankar Natarajan, FCA', role: 'Senior Partner · Tax & Transfer Pricing', image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=700&q=85', practice: 'Tax & Customs', court: 'ITAT / CESTAT', location: 'Chennai', years: 26, rating: '4.8', matters: '890', languages: 'English · Hindi · Tamil', badge: 'Tribunal Specialist' },
]

function AdvocatesPage() {
  const [query, setQuery] = useState('')
  const [practice, setPractice] = useState('All practices')
  const [court, setCourt] = useState('All courts')
  const [selected, setSelected] = useState(null)
  const filtered = useMemo(() => advocates.filter((advocate) => {
    const text = `${advocate.name} ${advocate.role} ${advocate.practice} ${advocate.location} ${advocate.languages}`.toLowerCase()
    return text.includes(query.toLowerCase()) && (practice === 'All practices' || advocate.practice === practice) && (court === 'All courts' || advocate.court === court)
  }), [query, practice, court])

  return (
    <main className="directory-page">
      <div className="announcement"><span className="pulse-dot" /> 24/7 GLOBAL NRI LEGAL DESK ACTIVE <span className="announcement-detail">Immediate chamber response time under 45 minutes</span><a href="/">Return to home <span className="material-symbols-outlined">arrow_forward</span></a></div>
      <header className="site-header directory-header"><a className="brand" href="/"><span className="brand-mark">⚖</span><span><strong>VAKKEEL</strong><small>& ASSOCIATES</small></span></a><nav><a href="/">The Firm</a><a href="/">Practice Areas</a><a className="active-nav" href="/advocates">Our Advocates</a><a href="/#insights">Legal Insights</a></nav><a className="header-cta" href="/#intake"><span className="material-symbols-outlined">calendar_month</span> Request counsel</a></header>

      <section className="directory-hero"><div><span className="eyebrow"><span className="material-symbols-outlined">verified</span> THE VAKKEEL COLLEGIUM</span><h1>Meet the counsel<br /><em>behind the strategy.</em></h1><p>A considered network of Senior Advocates, specialist practitioners and Advocates-on-Record, connected across India's most important courts and commercial centres.</p></div><div className="directory-stat"><span className="material-symbols-outlined">account_balance</span><strong>500+</strong><span>verified advocates<br />across 28 states & UTs</span></div></section>

      <section className="directory-content"><div className="directory-toolbar"><div><span className="eyebrow dark">ADVOCATE DIRECTORY</span><h2>Find your counsel.</h2></div><span className="result-count">Showing <strong>{filtered.length}</strong> of {advocates.length} advocates</span><div className="directory-filters"><label className="directory-search"><span className="material-symbols-outlined">search</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, specialty or language" /></label><select value={practice} onChange={(event) => setPractice(event.target.value)}><option>All practices</option>{[...new Set(advocates.map((advocate) => advocate.practice))].map((item) => <option key={item}>{item}</option>)}</select><select value={court} onChange={(event) => setCourt(event.target.value)}><option>All courts</option>{[...new Set(advocates.map((advocate) => advocate.court))].map((item) => <option key={item}>{item}</option>)}</select></div></div>
        <div className="advocate-grid">{filtered.map((advocate) => <article className="advocate-card" key={advocate.name}><div className="advocate-portrait"><img src={advocate.image} alt={advocate.name} /><span className="verified-chip"><span className="material-symbols-outlined">verified</span> Verified</span><span className="advocate-badge">{advocate.badge}</span></div><div className="advocate-body"><div className="advocate-title"><div><h3>{advocate.name}</h3><p>{advocate.role}</p></div><span className="rating"><span className="material-symbols-outlined">star</span>{advocate.rating}</span></div><div className="advocate-details"><span><span className="material-symbols-outlined">gavel</span>{advocate.practice}</span><span><span className="material-symbols-outlined">location_on</span>{advocate.location} · {advocate.court}</span><span><span className="material-symbols-outlined">translate</span>{advocate.languages}</span></div><div className="advocate-stats"><span><strong>{advocate.years}+</strong> years at bar</span><span><strong>{advocate.matters}</strong> matters led</span></div><div className="advocate-actions"><button type="button" onClick={() => setSelected(advocate)}>View profile <span className="material-symbols-outlined">arrow_forward</span></button><a href="/#intake" aria-label={`Book consultation with ${advocate.name}`}><span className="material-symbols-outlined">calendar_month</span></a></div></div></article>)}</div>{filtered.length === 0 && <div className="directory-empty"><span className="material-symbols-outlined">search_off</span><h3>No advocate matches your search.</h3><p>Try clearing a filter or searching a broader practice area.</p></div>}</section>

      <section className="directory-cta"><div><span className="eyebrow">NOT SURE WHO TO CHOOSE?</span><h2>Let the chamber route your matter.</h2><p>Share the nature of your dispute and our registry team will identify the right senior counsel for your jurisdiction and urgency.</p></div><a className="button gold-button" href="/#intake">Route my matter <span className="material-symbols-outlined">arrow_forward</span></a></section>
      <ClientContactActions />
      <footer><div className="footer-brand"><a className="brand" href="/"><span className="brand-mark">⚖</span><span><strong>VAKKEEL</strong><small>& ASSOCIATES</small></span></a><p>Premier legal counsel for India and the world.</p></div><div><span className="footer-label">Chambers</span><p>New Delhi · Mumbai · Kerala<br />Chandigarh · Bengaluru · Chennai</p></div><div><span className="footer-label">Contact</span><p>+91 6369717520<br />Vakkeelandassociates@gmail.com</p></div><div><span className="footer-label">Directory</span><p><a href="/">The firm</a><br /><a href="/">Practice areas</a></p></div></footer>
      {selected && <div className="modal-backdrop" role="presentation" onClick={(event) => event.target === event.currentTarget && setSelected(null)}><div className="advocate-modal" role="dialog" aria-modal="true"><button className="modal-close" type="button" onClick={() => setSelected(null)} aria-label="Close"><span className="material-symbols-outlined">close</span></button><img src={selected.image} alt={selected.name} /><div><span className="eyebrow dark">{selected.badge}</span><h2>{selected.name}</h2><p className="modal-role">{selected.role}</p><div className="profile-facts"><span><strong>{selected.rating}</strong> client rating</span><span><strong>{selected.years}+</strong> years at bar</span><span><strong>{selected.matters}</strong> matters led</span></div><p>Practices before the {selected.court} from {selected.location}, with focus on {selected.practice.toLowerCase()} matters. Languages: {selected.languages}.</p><a className="button urgent" href="/#intake">Request a consultation <span className="material-symbols-outlined">arrow_forward</span></a></div></div></div>}
    </main>
  )
}

export default AdvocatesPage
